import { post, del, get, put,postformdata } from "../api_helper";
import * as salonurl from "../apiurls/salon";

export const salonSignup = data => post(salonurl.SALON_SIGNUP, data)
export const postformdataSignup = data => postformdata(salonurl.SALON_SIGNUP_FORM, data)
export const addSalonServices = data => post(salonurl.ADD_SALON_SERVICES, data)
export const getSalonGroupAndServices = () => get(salonurl.GET_SALON_GROUP_AND_SERVICES)
export const getSalonServicesInfo = data => post(salonurl.GET_SALON_SERVICES_INFO, data)
export const updateSalonServicesDescription = data => post(salonurl.UPDATE_SALON_SERVICES_DESCRIPTION, data)
export const getSalonEmployeeDropDown = () => get(salonurl.SALON_GET_EMPLOYEE_DROPDOWN)
export const getSalonDiscountList = () => get(salonurl.GET_SALON_DISCOUNT_LIST)
export const getSalonProducts = data => get(salonurl.SALON_GET_PRODUCT, data)
export const updateSalonServicesDistribution = data => post(salonurl.UPDATE_SALON_SERVICE_DISTRIBUTION, data)
export const addSalonProducts = data => post(salonurl.SALON_ADD_PRODUCT, data)
export const getSalonPackageList = () => get(salonurl.GET_SALON_PACKAGE_LIST)
export const updatePackageDescription = data => put(salonurl.UPDATE_PACKAGE_DESCRIPTION, data)
export const updatePackageFinePrint = data => post(salonurl.UPDATE_PACKAGE_FINEPRINT, data)
export const updateSalonProducts = data => post(salonurl.SALON_UPDATE_PRODUCT, data)
export const getSalonPackageInfo = data => post(salonurl.GET_PACKAGE_INFO, data)
export const updateSalonServiceGroupName = data => post(salonurl.UPDATE_SALON_SERVICE_GROUP_NAME, data)
export const updatePackageDistribution = data => post(salonurl.UPDATE_PACKAGE_DISTRIBUTION, data)
export const addSalonPackage = data => post(salonurl.ADD_SALON_PACKAGE, data)
export const updateSalonServicesFinePrint = data => post(salonurl.UPDATE_SALON_SERVICE_FINEPRINT, data)
export const updateSalonPackage = data => post(salonurl.UPDATE_SALON_PACKAGE, data)
export const setNewPasswordInstructrction = data => post(salonurl.SET_NEW_PASS_INSTRUCTION, data)
export const activeMembershipAddOn = () => get(salonurl.ACTIVE_MEM_ADDON)
export const updateTeamEmployee = data => put(salonurl.UPDATE_EMPLOYEE, data)
export const addSalonDiscount = data => post(salonurl.ADD_SALON_DISCOUNT, data)
export const getSalonDiscountInfo = (data) => get(salonurl.GET_SALON_DISCOUNT_INFO,data)
export const getRota=()=> get(salonurl.GET_ROTA)
export const getSalonDiscountServiceInfo = (data) => get(salonurl.GET_SALON_DISCOUNT_SERVICE_INFO,data)
export const updateSalonDiscount = data => post(salonurl.UPDATE_SALON_DISCOUNT, data)
export const deleteSalonDiscount = data => del(salonurl.DELETE_SALON_DISCOUNT, data)
export const getSalonVouchers = data => get(salonurl.GET_SALON_VOUCHER_LIST, data)
export const addSalonVouchers = data => post(salonurl.ADD_SALON_VOUCHER, data)
export const updateSalonVouchers = data => post(salonurl.UPDATE_SALON_VOUCHER, data)
export const addTeamMemberRota = data => post(salonurl.ADD_TEAM_MEMBER_ROTA, data)
export const getWeekWorkingHour = data => post(salonurl.GET_WEEK_WORKING_HOUR, data)
export const updateTeamWorkingHour = data => post(salonurl.UPDATE_TEAM_WORK_HOUR, data)
export const getTeamDuty = data => post(salonurl.GET_TEAM_DUTY, data)


